// hello/core/svelte/hello.svelte
// -*- mode: svelte -*-
//   note       : Pinned with a Linguist modeline so it keeps its own segment on the bar.
// Svelte - Hello World! :: RAiNBOW_Hello-World
//   colour     : #ff3e00
//   hue        : 14.6 deg
//   layer      : core (byte-balanced rainbow bar)
//   upstream   : https://github.com/quxianp/RAiNBOW_Hello-World
//   reference  : see https://esolangs.org/ and https://rosettacode.org/

// Hello World!
// Hello World!
// rainbow-pad equal byte share keeps the language bar an even rainbow
// rainbow-pad one segment per Linguist coloured language
// rainbow-pad Svelte :: RAiNBOW_Hello-World
// rainbow-pad colour #ff3e00 :: padded to 100
// rainbow-pad padding comment: byte balancing for the rainbow bar
// rainbow-pad https://github.com/quxianp/RAiNBOW_Hello-World
// rainbow-pad equal byte share keeps the language bar an even rainbow
// rainbow-pad one segment per Linguist coloured language
// rainbow-pad Svelte :: RAiNBOW_Hello-World
// rainbow-pad colour #ff3e00 :: padded to 100
// rainbow-pad padding comment: byte balancing for the rainbow bar
// rainbow-pad https://github.com/quxianp/RAiNBOW_Hello-World
// rainbow-pad equal byte share keeps the language bar an even rainbow
// rainbow-pad one segment per Linguist coloured language
// rainbow-pad Svelte :: RAiNBOW_Hello-World
// rainbow-pad colour #ff3e00 :: padded to 100
// rainbow-pad padding comment: byte balancing for the rainbow bar
// rainbow-pad https://github.com/quxianp/RAiNBOW_Hello-World
// rainbow-pad equal byte share keeps the language bar an even rainbow
// rainbow-pad one segment per Linguist coloured language
// rainbow-pad Svelte :: RAiNBOW_Hello-World
// rainbow-pad colour #ff3e00 :: padded to 100
// rainbow-pad padding comment: byte balancing for the rainbow bar
// rainbow-pad https://github.com/quxianp/RAiNBOW_Hello-World
// rainbow-pad equal byte share keeps the language bar an even rainbow
// rainbow-pad one segment per Linguist coloured language
// rainbow-pad Svelte :: RAiNBOW_Hello-World
// rainbow-pad colour #ff3e00 :: pad

// hello/core/vue/hello.vue
// -*- mode: vue -*-
//   note       : Pinned with a Linguist modeline so it keeps its own segment on the bar.
// Vue - Hello World! :: RAiNBOW_Hello-World
//   colour     : #41b883
//   hue        : 153.3 deg
//   layer      : core (byte-balanced rainbow bar)
//   upstream   : https://github.com/quxianp/RAiNBOW_Hello-World
//   reference  : see https://esolangs.org/ and https://rosettacode.org/

// Hello World!
// Hello World!
// rainbow-pad equal byte share keeps the language bar an even rainbow
// rainbow-pad one segment per Linguist coloured language
// rainbow-pad Vue :: RAiNBOW_Hello-World
// rainbow-pad colour #41b883 :: padded to 100
// rainbow-pad padding comment: byte balancing for the rainbow bar
// rainbow-pad https://github.com/quxianp/RAiNBOW_Hello-World
// rainbow-pad equal byte share keeps the language bar an even rainbow
// rainbow-pad one segment per Linguist coloured language
// rainbow-pad Vue :: RAiNBOW_Hello-World
// rainbow-pad colour #41b883 :: padded to 100
// rainbow-pad padding comment: byte balancing for the rainbow bar
// rainbow-pad https://github.com/quxianp/RAiNBOW_Hello-World
// rainbow-pad equal byte share keeps the language bar an even rainbow
// rainbow-pad one segment per Linguist coloured language
// rainbow-pad Vue :: RAiNBOW_Hello-World
// rainbow-pad colour #41b883 :: padded to 100
// rainbow-pad padding comment: byte balancing for the rainbow bar
// rainbow-pad https://github.com/quxianp/RAiNBOW_Hello-World
// rainbow-pad equal byte share keeps the language bar an even rainbow
// rainbow-pad one segment per Linguist coloured language
// rainbow-pad Vue :: RAiNBOW_Hello-World
// rainbow-pad colour #41b883 :: padded to 100
// rainbow-pad padding comment: byte balancing for the rainbow bar
// rainbow-pad https://github.com/quxianp/RAiNBOW_Hello-World
// rainbow-pad equal byte share keeps the language bar an even rainbow
// rainbow-pad one segment per Linguist coloured language
// rainbow-pad Vue :: RAiNBOW_Hello-World
// rainbow-pad colour #41b883 :: padded to 100
